import Preloader from "@/components/Preloader";
import "@css/plugins.css";
import "@css/style.css";
import { Roboto, Syne } from "next/font/google";
import "./globals.css";
import State from "/context/context";

/** google fonts */
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});
const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-syne",
  display: "swap",
});

/** Font family */
const fontFamily = `${roboto.variable} ${syne.variable} `;

export const metadata = {
  title: "Jara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fontFamily}>
      <body>
        <State>
          <div className="jara_tm_all_wrap">
            <Preloader />
            {children}
          </div>
        </State>
      </body>
    </html>
  );
}
